### PR TITLE
I created some new patches and I want to upload them to your master branch

### PR DESCRIPTION
**Pull request by EvilGodEX**

### CODE REVIEW

**Comment by gesangtome** [comment]
Can one of the admins verify this patch?

**Comment by EvilGodEX** [comment]
> Can one of the admins verify this patch?

?Excuse me？

**Comment by gesangtome** [comment]
test this please

**Comment by gesangtome** [comment]
run test

**Comment by gesangtome** [comment]
kkk

**Comment by gesangtome** [comment]
@EVILGODEX
It looks like your patch has passed the test, but please merge 'Add files via upload' and 'Making nubia-mpdata.dtb' into one commit. Thanks for your contribution.

**Comment by EvilGodEX** [comment]
@GESANGTOME
Nice, good idea

**Comment by gesangtome** [comment]
run test

**Comment by gesangtome** [comment]
I well be merge

**Pull request merged**
